version: 2
jobs:
  test:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          make test

  deploy:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker-compose -f docker-compose.test.yml -p ci build
          docker tag ci_web2004-php8:latest mattrayner/lamp:latest
          docker tag ci_web2004-php8:latest mattrayner/lamp:latest-2004
          docker tag ci_web2004-php8:latest mattrayner/lamp:latest-2004-php8
          docker tag ci_web2004-php7:latest mattrayner/lamp:latest-2004-php7
          docker tag ci_web2004-php8:latest mattrayner/lamp:build-$CIRCLE_BUILD_NUM
          docker tag ci_web2004-php8:latest mattrayner/lamp:build-$CIRCLE_BUILD_NUM-2004
          docker tag ci_web2004-php8:latest mattrayner/lamp:build-$CIRCLE_BUILD_NUM-2004-php8
          docker tag ci_web2004-php7:latest mattrayner/lamp:build-$CIRCLE_BUILD_NUM-2004-php7

          docker tag ci_web1804-php8:latest mattrayner/lamp:latest-1804
          docker tag ci_web1804-php8:latest mattrayner/lamp:latest-1804-php8
          docker tag ci_web1804-php7:latest mattrayner/lamp:latest-1804-php7
          docker tag ci_web1804-php8:latest mattrayner/lamp:build-$CIRCLE_BUILD_NUM-1804
          docker tag ci_web1804-php8:latest mattrayner/lamp:build-$CIRCLE_BUILD_NUM-1804-php8
          docker tag ci_web1804-php7:latest mattrayner/lamp:build-$CIRCLE_BUILD_NUM-1804-php7

          docker push mattrayner/lamp:latest
          docker push mattrayner/lamp:latest-2004
          docker push mattrayner/lamp:latest-2004-php8
          docker push mattrayner/lamp:latest-2004-php7
          docker push mattrayner/lamp:latest-1804
          docker push mattrayner/lamp:latest-1804-php8
          docker push mattrayner/lamp:latest-1804-php7
          docker push mattrayner/lamp:build-$CIRCLE_BUILD_NUM
          docker push mattrayner/lamp:build-$CIRCLE_BUILD_NUM-2004
          docker push mattrayner/lamp:build-$CIRCLE_BUILD_NUM-2004-php7
          docker push mattrayner/lamp:build-$CIRCLE_BUILD_NUM-2004-php8
          docker push mattrayner/lamp:build-$CIRCLE_BUILD_NUM-1804
          docker push mattrayner/lamp:build-$CIRCLE_BUILD_NUM-1804-php7
          docker push mattrayner/lamp:build-$CIRCLE_BUILD_NUM-1804-php8

  deploy-tags:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker-compose -f docker-compose.test.yml -p ci build
          docker tag ci_web2004-php8:latest mattrayner/lamp:$CIRCLE_TAG
          docker tag ci_web2004-php8:latest mattrayner/lamp:$CIRCLE_TAG-2004
          docker tag ci_web2004-php7:latest mattrayner/lamp:$CIRCLE_TAG-2004-php7
          docker tag ci_web2004-php8:latest mattrayner/lamp:$CIRCLE_TAG-2004-php8
          docker tag ci_web1804-php8:latest mattrayner/lamp:$CIRCLE_TAG-1804
          docker tag ci_web1804-php7:latest mattrayner/lamp:$CIRCLE_TAG-1804-php7
          docker tag ci_web1804-php8:latest mattrayner/lamp:$CIRCLE_TAG-1804-php8

          docker push mattrayner/lamp:$CIRCLE_TAG
          docker push mattrayner/lamp:$CIRCLE_TAG-2004
          docker push mattrayner/lamp:$CIRCLE_TAG-2004-php7
          docker push mattrayner/lamp:$CIRCLE_TAG-2004-php8
          docker push mattrayner/lamp:$CIRCLE_TAG-1804
          docker push mattrayner/lamp:$CIRCLE_TAG-1804-php7
          docker push mattrayner/lamp:$CIRCLE_TAG-1804-php8

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy-tags:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
